name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: kse-bd8338bbe006/kse-labs-trusted-workflows/.github/workflows/go-ci.yaml@main
    secrets: inherit
    with:
      go-version: '1.21'
  ci-status:
    name: CI Status
    runs-on: self-hosted
    needs: [build]
    if: always()
    steps:
      - name: Check CI result
        shell: pwsh
        run: |
          if ("${{ needs.build.result }}" -ne "success") {
            Write-Host "CI failed"
            exit 1
          }
